name: full_moon_alert
description: Full Moon Alert

version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_markdown: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/phases/

  fonts:
    - family: Work Sans
      fonts:
        - asset: assets/font/WorkSans-Thin.ttf
          weight: 100
        - asset: assets/font/WorkSans-ExtraLight.ttf
          weight: 200
        - asset: assets/font/WorkSans-Light.ttf
          weight: 300
        - asset: assets/font/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/font/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/font/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/font/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/font/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: assets/font/WorkSans-Black.ttf
          weight: 900
    - family: AppIcons
      fonts:
        - asset: assets/icons/fonts/MyFlutterApp.ttf
